package Acme::CPANLists::Import::NEILB::Constants;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/constants.html] (retrieved on 2016-02-20). For the full article, visit the URL.",entries=>[{module=>"Attribute::Constant"},{module=>"Config::Constants"},{module=>"Const::Fast"},{module=>"Constant::FromGlobal"},{module=>"Constant::Generate"},{module=>"Devel::Constants"},{module=>"Lexical::Import"},{module=>"Lexical::Var"},{module=>"Scalar::Constant"},{module=>"Scalar::Construct"},{module=>"Scalar::Readonly"},{module=>"constant"},{module=>"constant::def"},{module=>"constant::defer"},{module=>"constant::lexical"},{module=>"constant::our"},{module=>"ex::constant::vars"}],summary=>"Defining constants (2012)"});

1;
# ABSTRACT: Defining constants (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/constants.html> (retrieved on 2016-02-20). For the full article, visit the URL.

