package Acme::CPANLists::Import::NEILB::Dependencies;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/dependencies.html] (retrieved on 2016-02-20). For the full article, visit the URL.",entries=>[{module=>"App::FatPacker::Trace"},{module=>"CPAN::Dependency"},{module=>"CPAN::FindDependencies"},{module=>"Devel::Dependencies"},{module=>"Devel::Modlist"},{module=>"Devel::TraceDeps"},{module=>"Devel::TraceLoad"},{module=>"Devel::TraceUse"},{module=>"Devel::VersionDump"},{module=>"Dist::Requires"},{module=>"HTML::Perlinfo::Loaded"},{module=>"Module::Dependency::Grapher"},{module=>"Module::Depends"},{module=>"Module::Extract::Use"},{module=>"Module::ExtractUse"},{module=>"Module::Info"},{module=>"Module::Inspector"},{module=>"Module::MakefilePL::Parse"},{module=>"Module::Overview"},{module=>"Module::ParseDeps"},{module=>"Module::ScanDeps"},{module=>"Module::Used"},{module=>"Perl::PrereqScanner"}],summary=>"Getting module dependency information (2012)"});

1;
# ABSTRACT: Getting module dependency information (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/dependencies.html> (retrieved on 2016-02-20). For the full article, visit the URL.

