package Acme::CPANLists::Import::NEILB::HTTPRequesters;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/http-requesters.html] (retrieved on 2016-02-20). For the full article, visit the URL.",entries=>[{module=>"Furl"},{module=>"HTTP::Client"},{module=>"HTTP::Lite"},{module=>"HTTP::Soup"},{module=>"HTTP::Tiny"},{module=>"LWP"},{module=>"LWP::Curl"},{module=>"LWP::Simple"},{module=>"Mojo::UserAgent"},{module=>"Net::Curl"},{module=>"Net::Curl::Simple"},{module=>"Net::HTTP"},{module=>"Net::HTTP::Tiny"},{module=>"URI::Fetch"},{module=>"URL::Grab"},{module=>"WWW::Curl"},{module=>"WWW::Curl::Simple"},{module=>"Web::Magic"}],summary=>"Making HTTP requests (2012)"});

1;
# ABSTRACT: Making HTTP requests (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/http-requesters.html> (retrieved on 2016-02-20). For the full article, visit the URL.

