package Acme::CPANLists::Import::NEILB::IPLocation;

# DATE
# VERSION

our @Module_Lists = ({entries=>[{module=>"Geo::Coder::HostIP"},{module=>"Geo::IP"},{module=>"Geo::IP2Location"},{module=>"Geo::IP::RU::IpGeoBase"},{module=>"Geo::IPfree"},{module=>"IP::Country"},{module=>"IP::Country::DB_File"},{module=>"IP::Country::DNSBL"},{module=>"IP::Info"},{module=>"IP::Location"},{module=>"IP::QQWry"},{module=>"IP::World"}],summary=>"Locating an IP address"});

1;
# ABSTRACT: Locating an IP address

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/ip-location.html>. For the full article, visit the URL.

