package Acme::CPANLists::Import::NEILB::LUHN;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/luhn.html] (retrieved on 2016-02-20). For the full article, visit the URL.",entries=>[{module=>"Algorithm::CheckDigits"},{module=>"Business::BankCard"},{module=>"Business::CardInfo"},{module=>"Regexp::Common"},{module=>"Regexp::Common::_support"}],summary=>"Checking credit card numbers (LUHN check) (2012)"});

1;
# ABSTRACT: Checking credit card numbers (LUHN check) (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/luhn.html> (retrieved on 2016-02-20). For the full article, visit the URL.

