package Acme::CPANLists::Import::NEILB::Markdown;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/markdown.html] (retrieved on 2016-02-20). For the full article, visit the URL.",entries=>[{module=>"Catalyst::Plugin::Markdown"},{module=>"DR::SunDown"},{module=>"Dist::Zilla::Plugin::ReadmeAnyFromPod"},{module=>"Email::Simple"},{module=>"Email::Simple::Markdown"},{module=>"HTML::WikiConverter"},{module=>"HTML::WikiConverter::Markdown"},{module=>"Markdent"},{module=>"Markdown::Pod"},{module=>"Markup::Unified"},{module=>"Pod::Markdown"},{module=>"Pod::Parser"},{module=>"Template"},{module=>"Template::Provider::Markdown"},{module=>"Text::Markdown"},{module=>"Text::Markdown::Discount"},{module=>"Text::Markdown::Hoedown"},{module=>"Text::Markup"},{module=>"Text::Markup::Any"},{module=>"Text::MultiMarkdown"}],summary=>"Modules for converting markdown to HTML (2013)"});

1;
# ABSTRACT: Modules for converting markdown to HTML (2013)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/markdown.html> (retrieved on 2016-02-20). For the full article, visit the URL.

