package Acme::CPANLists::Import::NEILB::ModuleLoading;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/module-loading.html] (retrieved on 2016-02-20). For the full article, visit the URL.",entries=>[{module=>"Acme::require::case"},{module=>"AnyLoader"},{module=>"Class::Autouse"},{module=>"Class::LazyLoad"},{module=>"Class::Load"},{module=>"Class::Load::XS"},{module=>"Class::Loader"},{module=>"ClassLoader"},{module=>"MAD::Loader"},{module=>"Module::Hash"},{module=>"Module::Implementation"},{module=>"Module::Load"},{module=>"Module::Load::Conditional"},{module=>"Module::Quote"},{module=>"Module::Recursive::Require"},{module=>"Module::Require"},{module=>"Module::Requires"},{module=>"Module::Runtime"},{module=>"Module::UseFrom"},{module=>"Mojo::Loader"},{module=>"Mrequire"},{module=>"Object::Trampoline"},{module=>"UNIVERSAL::require"},{module=>"above"},{module=>"aliased"},{module=>"all"},{module=>"autouse"},{module=>"base"},{module=>"lib::require::all"},{module=>"only"},{module=>"parent"},{module=>"pkg"},{module=>"provide"},{module=>"relative"},{module=>"superclass"},{module=>"syntax"},{module=>"use"}],summary=>"Modules that (can) load other modules (2013)"});

1;
# ABSTRACT: Modules that (can) load other modules (2013)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/module-loading.html> (retrieved on 2016-02-20). For the full article, visit the URL.

