package Acme::CPANLists::Import::NEILB::ModulePath;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/module-path.html] (retrieved on 2016-02-20). For the full article, visit the URL.",entries=>[{module=>"App::moduleswhere"},{module=>"App::whichpm"},{module=>"Class::Inspector"},{module=>"Module::Data"},{module=>"Module::Filename"},{module=>"Module::Finder"},{module=>"Module::Info"},{module=>"Module::Locate"},{module=>"Module::Mapper"},{module=>"Module::Metadata"},{module=>"Module::Path"},{module=>"Module::Util"},{module=>"Path::ScanINC"},{module=>"Pod::Perldoc"}],summary=>"Getting a module's path (2012)"});

1;
# ABSTRACT: Getting a module's path (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/module-path.html> (retrieved on 2016-02-20). For the full article, visit the URL.

