package Acme::CPANLists::Import::NEILB::Passwords;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/passwords.html] (retrieved on 2016-02-20). For the full article, visit the URL.",entries=>[{module=>"App::Genpass"},{module=>"Benchmark"},{module=>"Crypt::GeneratePassword"},{module=>"Crypt::PW44"},{module=>"Crypt::RandPasswd"},{module=>"Crypt::XkcdPassword"},{module=>"Crypt::YAPassGen"},{module=>"Data::Random"},{module=>"Data::Random::String"},{module=>"Data::SimplePassword"},{module=>"Session::Token"},{module=>"String::MkPasswd"},{module=>"String::Random"},{module=>"String::Urandom"},{module=>"Text::Password::Pronounceable"}],summary=>"Generating passwords (2012)"});

1;
# ABSTRACT: Generating passwords (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/passwords.html> (retrieved on 2016-02-20). For the full article, visit the URL.

