package Acme::CPANLists::Import::NEILB::Passwords;

# DATE
# VERSION

our @Module_Lists = ({entries=>[{module=>"App::Genpass"},{module=>"Benchmark"},{module=>"Crypt::GeneratePassword"},{module=>"Crypt::PW44"},{module=>"Crypt::RandPasswd"},{module=>"Crypt::XkcdPassword"},{module=>"Crypt::YAPassGen"},{module=>"Data::Random"},{module=>"Data::Random::String"},{module=>"Data::SimplePassword"},{module=>"Session::Token"},{module=>"String::MkPasswd"},{module=>"String::Random"},{module=>"String::Urandom"},{module=>"Text::Password::Pronounceable"}],summary=>"Generating passwords"});

1;
# ABSTRACT: Generating passwords

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/passwords.html>. For the full article, visit the URL.

