package Acme::CPANLists::Import::NEILB::SpellNumbers;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/spell-numbers.html]. For the full article, visit the URL.",entries=>[{module=>"Lingua::EN::Inflect"},{module=>"Lingua::EN::Numbers"},{module=>"Math::BigInt::Named"}],summary=>"Spelling out a number in English"});

1;
# ABSTRACT: Spelling out a number in English

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/spell-numbers.html>. For the full article, visit the URL.

