package Acme::CPANLists::Import::NEILB::UserAgent;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/user-agent.html] (retrieved on 2016-02-20). For the full article, visit the URL.",entries=>[{module=>"HTML::ParseBrowser"},{module=>"HTTP::BrowserDetect"},{module=>"HTTP::DetectUserAgent"},{module=>"HTTP::Headers::UserAgent"},{module=>"HTTP::MobileAgent"},{module=>"HTTP::MobileAgent::Flash"},{module=>"HTTP::UserAgentString::Parser"},{module=>"Mobile::UserAgent"},{module=>"Parse::HTTP::UserAgent"},{module=>"Woothee"}],summary=>"Parsing User-Agent strings (2012)"});

1;
# ABSTRACT: Parsing User-Agent strings (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://neilb.org/reviews/user-agent.html> (retrieved on 2016-02-20). For the full article, visit the URL.

